version: "3.8"

services:

    # --- --- --- --- ---
        # the 'web' service serves the finished static website
    # --- --- --- --- ---
    web:
        image: nginx:1.19.2-alpine
        container_name: web-nginx
        volumes:
            - ./frontend/dist:/usr/share/nginx/html:ro
            - ./nginx-conf/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx-conf/conf.d/world-united.conf:/etc/nginx/conf.d/world-united.conf
            # - /etc/letsencrypt:/etc/letsencrypt
        ports:
            - 80:80
            - 443:443

    # --- --- --- --- ---
        # the 'dev' service runs a node-js container that is used for 'nuxt dev' (development server) and 'nuxt generate' (SSG build)
    # --- --- --- --- ---
    dev:
        image: node:14.12.0-stretch-slim
        container_name: dev-nodejs
        user: node
        working_dir: /home/node/frontend
        # command: /bin/bash -c "npm install && npm run dev"
        command: tail -f /dev/null      # idle process   # connect via designated shell 'docker-compose exec dev bash', and then start your dev scripts
        volumes:
            - ./frontend:/home/node/frontend
        ports:
            - 3333:3333  # port for nuxt dev server
