<template>
    <main class="PrivacyPolicyPage">
        <div class="centered-body-column">
            <Card :heading="'Privacy Policy'" :isSuperHeading="false">
                <h4>Introduction</h4>
                
                <p>
                    This privacy policy page is intended to make it transparent to the user how we handle their personal data. It explains in detail which personal data we process and store.
                </p>

                <h4>Informal Abstract</h4>

                <p>
                    We only collect the data necessary to ensure the primary functions of our website. We delete any user data as soon as our hoster allows it.
                    <br>
                    As a non-profit organisation our sole intent is to contribute to a save and pleasent user experience. Therefore we naturally refrain from using cookies, tracking and profiling.
                </p>

                <h4>Processing of personal data</h4>

                <p>
                    The way the internet works necessitates that our website processes a series of data and information when a user or automated system calls up the website in order to be able to deliver the content. This information includes:
                </p>
                <ul>
                    <li>the browser type and version used,</li>
                    <li>the operating system used by the accessing system,</li>
                    <li>the website from which an accessing system reaches our website (so-called referrers),</li>
                    <li>the sub-websites,</li>
                    <li>the date and time of access to the Internet site,</li>
                    <li>an Internet protocol address (IP address),</li>
                    <li>the Internet service provider of the accessing system</li>
                    <li>any other similar data and information</li>
                </ul>

                <h4>Legal basis for the processing</h4>

                <p>
                These processing operations are based on Article 6(1) lit. f GDPR for the purposes of the legitimate interests pursued by our organisation, which is to ensure the technical functionality of our website.
                </p>

                <h4>External hosting service</h4>

                <p>
                Our website is hosted by an external service provider (hoster). Our hoster has access to the information listed above in the interest of a secure, fast and efficient provision of our online service by a professional provider (Article 6(1) lit. f GDPR).
                </p>

                <p>
                We have concluded a GDPR Data Processing Agreement (DPA) with our hoster in order to ensure data proctection compliant processing. This DPA legally requires the hoster to process personal data exclusively for the purpose of meeting their performance obligations and to not store any more data than we do.
                </p>

                <p>
                We use the following hoster:<br>
                BIOHOST - Lars-Helge Wilbrandt<br>
                Nahrungsberg 70<br>
                35390 Gießen<br>
                <a href="https://www.biohost.de/" target="_blank" rel="noopener noreferrer">https://www.biohost.de/</a>
                </p>

                <h4>Deletion of all personal data</h4>

                <p>
                Our hoster stores the data mentioned above in log files. These files are deleted on the eighth day after the user visited our website. We do not use any cookies, tracking tools or profiling software.
                </p>

                <h4> Additional transparancy </h4>

                <p>
                    Our website is open source, meaning that you can find the its source code <a href="https://github.com/terra-utopia/terra-utopia-website" target="_blank" rel="noopener noreferrer">on Github</a>.
                </p>

                <h4>Contact</h4>
                <p>
                    For any questions related to the privacy policy, you may at any time contact us at <a href="mailto:contact@terra-utopia.world" target="_blank">contact@terra-utopia.world</a>.
                </p>
                <br>

                <p>This Privacy Policy has partially been generated by the Privacy Policy Generator of the <a href="https://dg-datenschutz.de/services/external-data-protection-officer/?lang=en">External Data Protection Officers</a> that was developed in cooperation with the <a href="https://www.wbs-law.de/eng/practice-areas/media-law/">Media Law Lawyers</a> from WBS-LAW.
                </p>
                

                <!-- IF WE CHOOSE TO USE LOG FILES (WITH PERSONAL DATA LIKE IP ADDRESSES!) IN THE FUTURE ...

                    The website of the Terra Utopia collects a series of general data and information when a data subject or automated system calls up the website. This general data and information are stored in the server log files.

                    ...

                    When using these general data and information, the Terra Utopia does not draw any conclusions about the data subject. Rather, this information is needed to (1) deliver the content of our website correctly, (2) optimize the content of our website as well as its advertisement, (3) ensure the long-term viability of our information technology systems and website technology, and (4) provide law enforcement authorities with the information necessary for criminal prosecution in case of a cyber-attack. Therefore, the Terra Utopia analyzes anonymously collected data and information statistically, with the aim of increasing the data protection and data security of our enterprise, and to ensure an optimal level of protection for the personal data we process. The anonymous data of the server log files are stored separately from all personal data provided by a data subject.
                -->
            </Card>
        </div>
    </main>
</template>



<style lang="scss" scoped>
@import '~/assets/shared-styles.scss';
.PrivacyPolicyPage{
    .centered-body-column {
        width: 95%;
        max-width: 960px;
        margin: 0 auto;

        .Card {
            margin-bottom: 32px;
            box-shadow: 0px 4px 20px rgba(0, 0, 0, 0.4), 0 4px 50px rgba(0,0,0, 0.25);
            text-align: left;
            

            & > p {  // prevents that any children '<p>' elements are selected
                @include d-small-text;
                margin: 10px 0;

                .highlighted {
                    @include semi-bold-italic;
                }
            }

            & ul {
                @include d-small-text;
                margin-left: 30px;
            }

            & a{
                text-decoration: underline;
                
                &:hover{
                    opacity: .8;
                }
            }
        }
    }
}
</style>